names<-c("Bhanu","Sai","Uma")
age<-c(22,22,21)
marks<-c(99,98,99)
df<-data.frame(names,age,marks)
mean(df $age)
write.csv(df,"datafr.csv")

names<-c("Bhanu","Sai","Uma")
age<-c(22,22,21)
marks<-c(99,98,99)
df<-data.frame(names,age,marks)
median(df $age)
write.csv(df,"datafr.csv")

names<-c("Bhanu","Sai","Uma")
age<-c(22,22,21)
marks<-c(99,98,99)
df<-data.frame(names,age,marks)
mode(df $age)
write.csv(df,"datafr.csv")
